### ISSUE TITLE
DocReview

### ISSUE THREAD

**Issue by rslruiz** [jvcreyes/OOOrangeProject#2]
- [x] The readme does not explain how the process of SLP, ETH and AXS will happen. 

- [x] The conversion process is ourside the readme file, it should be included in the Readme.md file.
 
- [x] The requirements doesn't seem to have the definition of the nouns and as well as the verbs so in my suggestion it must be completed, it needs more improvement. 

- [x] The py scripts as well are complete though PEP8 needs a minimal improvement.

**Comment by jvcreyes** [comment]
Issues properly addressed.
